[package]
name = "pallete"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Pallete — кроссплатформенный сборщик палитр"

[lib]
name = "pallete_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
parser = { path = "../crates/parser" }
uuid = { workspace = true }
chrono = { workspace = true }
dirs = "5"

[dev-dependencies]
tempfile = "3"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
